[package]
name = "talechime-core"
version = "0.3.0"
edition = "2024"
rust-version = "1.89"
description = "Session, synthesis and playback core for novel-tts"
authors = ["yexiyue <yexiyue666@qq.com>"]
license = "MIT"
keywords = ["Novel", "TTS"]
repository = "https://github.com/yexiyue/talechime"

[dependencies]
anyhow.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tts-protocol = { package = "talechime-protocol", path = "../talechime-protocol", version = "0.1.0" }
regex.workspace = true
reqwest.workspace = true
rodio.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
